name: base_1
description: "Simple base project with flutter_bloc"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: 1.0.2
  cached_network_image: 3.3.1
  pull_to_refresh: 2.0.0
  scroll_to_index: 3.0.1
  flutter_smart_dialog: 4.9.6

  # Network
  dio: 5.0.2
  pretty_dio_logger: 1.3.1

  # DI
  injectable: 2.1.0
  get_it: 7.2.0

  # Model gen
  freezed: 2.5.0
  copy_with_extension: 5.0.2

  # State management
  flutter_bloc: 8.1.2
  equatable: 2.0.5
  dartz: 0.10.1

  # env
  flutter_dotenv: 5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  injectable_generator: 2.1.4
  build_runner: 2.3.3
  json_serializable: 6.6.0
  retrofit_generator: 6.0.0+1
  copy_with_extension_gen: 5.0.2
  flutter_gen_runner: 5.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - assets/images/

flutter_gen:
  output: lib/core/assets_gen/
  assets:
    enable: true
  font:
    enable: true